### ISSUE TITLE
Instalar las aplicaciones necesarias.

### ISSUE THREAD

**Issue by Justinsegurar** [AnthonyAS15/Introduccion-a-HDL#1]
## Instalación Vivado 
- Para esta parte, realizaremos la correcta instalación del programa de Vivado, con el cual, se trabajará a lo largo del proyecto "Instalación a diseño digital en HDL".
 ## Objetivos 
### Objetivo General:
- Descargar el programa Vivado para el uso en el proyecto "Instalación a diseño digital en HDL"
### Objetivos Específicos:
- Identificar el programa Vivado y su uso para la realización correcta del proyecto.
- Determinar la correcta instalación del programa Vivado en cada una de las computadoras del grupo.
## Fecha de entrega
- Instalar el programa antes del jueves 22 de septiembre del 2022
## Colaboradores asignados
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by Justinsegurar** [comment]
## Instalación 
- En la instalación del programa Vivado 2018.3 tuve varias dificultades a la hora de descargarlo, debido a que no me dejaba instalarlo de la manera correcta, entonces acudí a la ayuda del Prof. Kaleb Alfaro Badilla, el cual me proporcionó el link de instalación del programa y que debía de instalar, esta ayuda la recibí el día viernes 9 de septiembre, sin embargo, yo acudí a la instalación el día martes 20 de septiembre y hasta la fecha el programa sigue en instalación...

**Comment by AnthonyAS15** [comment]
## Instalación 
- Al igual que el compañero, presenté dificultades al instalar el programa Vivado 2018.3. La razón de lo anterior, radicó en un problema con la validación de la cuenta, sin embargo, esto pudo ser solucionado al usar el correo institucional, en lugar del personal.

**Comment by ElRiquitix** [comment]
## Instalación 
- Tras varias complicaciones, debido a la dificultad de la instalación del  Vivado 2018.3, gracias a la ayuda del profesor y mis propios compañeros pude solucionar los problemas de instalación y de validación de la cuenta. Sin embargo, todavía me falta comprender mas de la aplicación, pero es un proceso progresivo.
