### ISSUE TITLE
Hacer una prueba de encender un led con un switch

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/Introduccion-a-HDL#15]
## Hacer una prueba de encender un led con un switch
- Para esta parte, realizaremos pruebas para encender un led a partir del movimiento de un conmutador en la FPGA.
 ## Objetivos 
### Objetivo General:
- Hacer las pruebas correspondientes con el software Vivado y la FPGA Nexys 4 DDR.
### Objetivos Específicos:
- Escribir el código que realiza el fin deseado.
- Aplicar las restricciones necesarias para que las entradas y salidas estén bien definidas.
## Fecha de entrega
- Hacer las pruebas antes del domingo 2 de octubre del 2022
## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by AnthonyAS15** [comment]
## Pruebas
- Las pruebas fueron llevadas a cabo con éxito.

**Comment by Justinsegurar** [comment]
## Observación de la prueba realizada 
- En esta prueba se puede observar, que al elevar los dos primeros switch, se va a encender el segundo led, esto se da debido a que estamos trabajando con el bit "0010" o bien el numero decimal "2". Esto se puede llegar a comprobar por medio de la siguiente tabla. 

## Código de Gray 


![Image](https://user-images.githubusercontent.com/111217127/193497302-76e77e65-9c70-46af-a7ca-36844bef4845.png)

## Prueba realizada


![Image](https://user-images.githubusercontent.com/111217127/193497361-42e4c858-a74d-4a92-a506-b17353669a57.jpg)

**Comment by ElRiquitix** [comment]
## Observación de la prueba realizada 
- En esta prueba se puede observar, que al elevar los dos primeros switch, se va a encender el segundo led, esto se da debido a que estamos trabajando con el bit "0010" o bien el numero decimal "2". Esto se puede llegar a comprobar por medio de la siguiente tabla. 

## Prueba realizada


![Image](https://user-images.githubusercontent.com/111217127/193497361-42e4c858-a74d-4a92-a506-b17353669a57.jpg)

**Comment by ElRiquitix** [comment]
## Prueba realizada "Encender luz LED" 

Realizamos pruebas para encender un led a partir del movimiento de un conmutador en la FPGA (Switch).

-Ejemplo: Primer Switch primer Led




![Image](https://user-images.githubusercontent.com/110042626/194457891-0c3dc333-c69a-4686-9b4f-6067f6130a66.jpg)
