### ISSUE TITLE
Crear el archivo README (Semana 9).

### ISSUE THREAD

**Issue by Justinsegurar** [AnthonyAS15/Introduccion-a-HDL#2]
## README
- Para esta parte, se creará y actualizará el archivo README, el cual va a contener la información necesaria del proyecto, con el fin de ir realizando los objetivos presentados a la semana 9

## Fecha de entrega
- Actualizar el archivo antes del domingo 02 de octubre del 2022

## Colaboradores asignados
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by AnthonyAS15** [comment]
El archivo README fue creado y actualizado con éxito con las descripciones del funcionamiento del circuito completo y de cada subsistema.
