### ISSUE TITLE
Actualizar el archivo README (Semana 10).

### ISSUE THREAD

**Issue by Justinsegurar** [AnthonyAS15/Introduccion-a-HDL#3]
## README
- Para esta parte, se actualizará el archivo README, el cual va a contener la información necesaria del proyecto, con  el fin de ir realizando los objetivos presentados a la semana 10

## Fecha de entrega
- Actualizar el archivo antes del martes 04 de octubre del 2022

## Colaboradores asignados
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by Justinsegurar** [comment]
El README fue actualizado con éxito, con todos los cambios y recomendaciones dados, con el fin de verificar el funcionamiento correcto del mismo.

**Comment by AnthonyAS15** [comment]
Debido a algunas complicaciones con el subsistema 3, la elaboración de diagramas y la creación de las simulaciones, hemos presentado un atraso en la actualización del README.
