### ISSUE TITLE
Revisar el archivo README.

### ISSUE THREAD

**Issue by Justinsegurar** [AnthonyAS15/Introduccion-a-HDL#7]
## README
- Para esta parte, se revisará y corregirá , si es necesario, el archivo README. Lo anterior se realiza con el fin de comprobar que todo esté correcto antes de la entrega final del proyecto.

## Fecha de entrega
- Revisar y corregir el archivo antes del martes 11 de octubre del 2022

## Colaboradores asignados
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by AnthonyAS15** [comment]
El archivo fue revisado y corregido con éxito.
